# TARGET = a.out
# SOURCE = test.c
# DEPEND = test.o



# all: $(TARGET)

# a.out: $(DEPEND)
# 	gcc $(DEPEND) -o $(TARGET)

# $(DEPEND):
# 	gcc -c $(SOURCE)

# clean: 
# 	rm -rf $(TARGET)*.o

run:
	@gcc -Wall -o test test.c




